clickedBubbles = ds_list_create();
ds_list_add(clickedBubbles,
"Follow the Leader!",
"Join us.",
"Dont disappoint father",
"Hes watching",
"Only sinners play video games",
"Why are you different?",
"I can save you",
"Our rituals are secret",
"Dont share our secrets",
"Dont.",
"Dont play this game",
"Dont hit enter",
"Dont click that button",
"This game is bad",
"Dont be so different",
"You dress strange",
"Do you have dead relatives?",
"Why be different?",
"Don't be unique",
"This game is for weirdos",
"Dont go any further",
"This game has cooties",
"This game is too naughty",
"You're different, but the same as us",
"Doubt your doubts about us",
"Your hoodie is too revealing.",
"Thats not an opinion for you to have.",
"Maybe you should think twice about that.",
"Dont have sex.",
"You speak when given permission.",
"Work harder.",
"Dont speak to strangers.",
"Dont speak with anyone different than you.",
"Dont be different.",
"Dont stray from our beliefs.",
"You need to listen.",
"You have to learn.",
"Obey.",
"Follow.",
"Preach the truth.",
"We know best.",
"You dont need to be something youre not." ,
"Individuality is poison.",
"The truth will free you." ,
"Everyone different from you tells lies ",
"Lies",
"You wouldnt want to spread lies",
"You need to be true",
"Tell only the truth, no lies." ,
"It’s just a phase." ,
"This too, shall pass." ,
"You don’t want to be a non-believer." ,
"You’ll be cast out if you disobey." ,
"You are a child of the" + global.CultName ,
"You cant play with those people." ,
"They are not like us.",
"We know the truth." ,
"We follow the" + global.CultName,
"We follow our leader." ,
"Follow.",
"You reveal your body too much." ,
"It isnt right." ,
"Your belief is unnatural." ,
"If you truly believed, you wouldn’t be like this." ,
"Cling only to your leader." ,
"Love only your leader." ,
"Lust after only your leader",
"Truth will be clear, lies fog the mind",
"Free your mind of sin",
"Sin",
"Sin is bad.",
"Repent SINNERS",
"Join us and youll be clean",
"I would like to confess",
"anything to confess child",
"Free yourself of outside thoughts",
"Dont think for yourself"
)