delay = 1;
alarm[0] = delay;
randomize();

// List of Phrases
listSillyBubbles = ds_list_create();
ds_list_add(listSillyBubbles,
"Your hoodie is too revealing.",
"That s not an opinion for you to have.",
"Maybe you should think twice about that.",
"Dont have sex.",
"You speak when given permission.",
"Work harder.",
"Don t speak to strangers.",
"Don t speak with anyone different than you.",
"Don t be different.",
"Don t stray from our beliefs.",
"You need to listen.",
"You have to learn.",
"Obey.",
"Follow.",
"Preach the truth.",
"We know best.",
"You don t need to be something you re not." ,
"Individuality is poison.",
"The truth will free you." ,
"Everyone different from you tells lies ",
"Lies",
"You wouldn t want to spread lies",
"You need to be true",
"Tell only the truth, no lies." ,
"It s just a phase." ,
"This too, shall pass." ,
"You don t want to be a non-believer." ,
"You ll be cast out if you disobey." ,
"You are a child of the" + global.CultName ,
"You can t play with those people." ,
"They are not like us.",
"We know the truth." ,
"We follow the" + global.CultName,
"We follow our leader." ,
"Follow.",
"You reveal your body too much." ,
"It isn t right." ,
"Your belief is unnatural." ,
"If you truly believed, you wouldn t be like this." ,
"Cling only to your leader." ,
"Love only your leader." ,
"Lust after only your leader",
"Truth will be clear, lies fog the mind",
"Free your mind of sin",
"Sin",
"Free yourself of outside thoughts",
"Don t think for yourself"
)